### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ElementAffect' of undefined - Browserify

### ISSUE THREAD

**Issue by polikin** [domsammut/jQuery-ScrollAppear#2]
js:
```
$('.test').ScrollAppear({
        ElementAffect: '.itemtwo',
        AddClass: 'itemthree'
});
```

html:
```
<div class="test"></div>
<div class="itemtwo">item two</div>
```

Error: `Uncaught TypeError: Cannot read property 'ElementAffect' of undefined`

**Comment by domsammut** [comment]
Hi Polikin,

Thanks for the feedback. Can you provide a bit more context (full HTML / JS) and if you're using Browserify shim. I was able to make jQuery ScrollAppear work successfully without errors (I didn't use Browserify shim).

Thanks
Dom

**Comment by polikin** [comment]
Well.. I found something.. it's seem that ScrollAppear conflict with FancySelect script.

**Comment by domsammut** [comment]
Ah okay. Are you running both through Browserify? Can you send me through an example for reference to see if I resolve the issue from my end (and potentially any other plugins). 

Thanks
Dom

**Comment by polikin** [comment]
can you give me your email.

**Comment by domsammut** [comment]
Hi Polikin,

Feel free to just put it in [JSFiddle](https://jsfiddle.net/) or similar service (like [gist](http://gist.github.com)). I'd rather not distribute my email address.

Thanks for understanding
Dom

**Comment by polikin** [comment]
yeah, no problem. You can download my code here: http://ge.tt/6nSwHwO2/v/0

let me know when you got the file.

**Comment by domsammut** [comment]
Hi Polikin,

Can you please upload this code somewhere that is readable. I don't download zip files from untrusted sources.

Thanks
Dom

**Comment by polikin** [comment]
I understand, but won't be able to see the error id you don't have my structure.

**Comment by domsammut** [comment]
I don't need the entire site If you can document the structure of your files and then provide links to the relevant HTML / JS via gist/jsfiddle I should have enough to go from.

**Comment by domsammut** [comment]
Example of issue not supplied. Closing until proper format is supplied (gist/jsfiddle/inline).
